name: "Build and Release APK"

on:
  push:
    branches:
      - master

jobs:
  export-android:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Godot 4.6
        run: |
          wget https://github.com/godotengine/godot/releases/download/4.6-stable/Godot_v4.6-stable_linux.x86_64.zip
          unzip Godot_v4.6-stable_linux.x86_64.zip
          mv Godot_v4.6-stable_linux.x86_64 godot.exec
          mkdir -p ~/.local/share/godot/export_templates/4.6.stable
          wget https://github.com/godotengine/godot/releases/download/4.6-stable/Godot_v4.6-stable_export_templates.tpz
          unzip Godot_v4.6-stable_export_templates.tpz -d ~/.local/share/godot/export_templates/4.6.stable
          mv ~/.local/share/godot/export_templates/4.6.stable/templates/* ~/.local/share/godot/export_templates/4.6.stable/

      # Creamos la carpeta exacta que requiere tu export_presets.cfg
      - name: Create Export Directory
        run: mkdir -p export

      - name: Build APK
        env:
          ANDROID_HOME: ${{ env.ANDROID_HOME }}
        run: |
          # El comando --export-release "Android" fuerza a Godot a ignorar Windows y Web por completo
          ./godot.exec --headless --path . --export-release "Android" export/Taino_Culture.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v0.1.${{ github.run_number }}
          name: "Taino Culture - Build ${{ github.run_number }}"
          files: export/Taino_Culture.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
